build_arguments:
- -destination
- platform="iOS Simulator,name=iPhone 14 Pro,OS=16.2"

format: xcode

disable_redundant_public_analysis: false
disable_update_check: false
external_encodable_protocols: false
retain_assign_only_properties: false
retain_assign_only_property_types: false
retain_objc_accessible: false
retain_public: false # очень много false positives от этой настройки, лучше держать её в true :(
retain_unused_protocol_func_params: false

clean_build: true
skip_build: false

strict: false

quiet: false
verbose: true

schemes:
- Pomogator

targets:
- Pomogator

project: Pomogator.xcodeproj
