# for swiftlint v. 0.56.1

analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

disabled_rules:
  - attributes
  - blanket_disable_command
  - contrasted_opening_brace
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - file_length
  - file_name
  - file_types_order
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicitly_unwrapped_optional
  - inclusive_language
  - indentation_width
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - object_literal
  - one_declaration_per_file
  - prefer_nimble
  - required_deinit
  - trailing_closure
  - sorted_enum_cases
  - switch_case_on_newline
  - type_name
  - vertical_whitespace_between_cases

# deprecated
  - inert_defer
  - unused_capture_list

opt_in_rules:
  - all

excluded:
  - Pods
  - Carthage
  - DerivedData

cyclomatic_complexity:
  ignores_case_statements: true

line_length:
  warning: 140

nesting:
  type_level: 3

custom_rules:
  wrong_letter:
    included: ".*\\.swift"
    regex: '[а-яА-Я][a-zA-Z]'
    name: "Wrong russian or english letter"
    message: "Replace latter to correct"
    severity: error

  insecure_url_usage:
    included: ".*\\.swift"
    regex: '(http):\/\/(www\.)?+[^\s\/\$.?#]+.[\S]+[$\s]'
    name: "Insecure url usage"
    match_kinds:
      - argument
      - buildconfig.id
      - buildconfig.keyword
      - identifier
      - keyword
      - objectliteral
      - parameter
      - placeholder
      - string
      - string_interpolation_anchor
    message: "Don't use http for urls. Replace with https"
    severity: error

  testable_import:
    included: ".*\\.swift"
    # Исключая файлы содержащие в пути директории Tests или Mocks или заканчивающиеся на 'Test(s).swift', 'Mock.swift', 'Stub.swift', 'Fake.swift'
    excluded: "(\\/Tests\\/.+|\\/Mocks\\/.*|Tests*|Mock|Stub|Fake)\\.swift$"
    name: "@testable import"
    regex: "@testable import"
    message: "Use testable imports only in test classes"
    severity: error
